In [1]:
print 2

2


In [2]:
x= 7

In [3]:
x

7

In [4]:
import numpy
import sklearn


In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame()


In [7]:
left_frame = pd.DataFrame({'key': range(5), 
                           'left_value': ['a', 'b', 'c', 'd', 'e']})
right_frame = pd.DataFrame({'key': range(2, 7), 
                           'right_value': ['f', 'g', 'h', 'i', 'j']})
print(left_frame)
print('\n')
print(right_frame)

   key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j


In [8]:

pd.merge(left_frame, right_frame, on='index', how='inner')

KeyError: 'index'

In [9]:
pd.concat([left_frame, right_frame])

key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c         NaN
3    3          d         NaN
4    4          e         NaN
0    2        NaN           f
1    3        NaN           g
2    4        NaN           h
3    5        NaN           i
4    6        NaN           j

In [10]:
pd.concat([left_frame, right_frame],axis=1)

key left_value  key right_value
0    0          a    2           f
1    1          b    3           g
2    2          c    4           h
3    3          d    5           i
4    4          e    6           j

In [11]:
left_frame


key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e

In [12]:
right_frame

key right_value
0    2           f
1    3           g
2    4           h
3    5           i
4    6           j

In [13]:
d = np.dataframe()

NameError: name 'np' is not defined

In [14]:
d = pd.dataframe()

AttributeError: 'module' object has no attribute 'dataframe'

In [15]:
v = pd.DataFrame()

In [16]:
v.append(1)

TypeError: cannot concatenate a non-NDFrame object

In [17]:
v.columns = ['review', 'sentiment']

ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements

In [18]:
v.append({0:'s'})

TypeError: Can only append a Series if ignore_index=True or if the Series has a name

In [19]:
df = pd.DataFrame()
df = df.append({'name': 'Zed', 'age': 9, 'height': 2}, ignore_index=True)

In [20]:
df


age  height name
0  9.0     2.0  Zed

In [21]:

df = df.append({'name': 'Zed', 'age': 9, 'height': 2}, ignore_index=True)

In [22]:
df


age  height name
0  9.0     2.0  Zed
1  9.0     2.0  Zed

In [23]:
df = pd.DataFrame()
df = df.append(2, ignore_index=True)

TypeError: cannot concatenate a non-NDFrame object

In [24]:
df = pd.DataFrame()
df = df.append({9: 2}, ignore_index=True)

In [25]:
df


9
0  2.0

In [26]:
for i, row in df.iterrows():
    print i, row

0 9    2.0
Name: 0, dtype: float64


In [27]:
for i, row in df.iterrows():
    print i, row, "--"

0 9    2.0
Name: 0, dtype: float64 --


In [28]:
for i, row in df.iterrows():
    print i

0


In [29]:
for i, row in df.iterrows():
    print i, row

0 9    2.0
Name: 0, dtype: float64


In [36]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print a
b = np.array([[5, 6]])
print 'b - ',b
np.concatenate((a, b), axis=0)
# array([[1, 2],
#        [3, 4],
#        [5, 6]])
np.concatenate((a, b.T), axis=1)
# array([[1, 2, 5],
#        [3, 4, 6]])

[[1 2]
 [3 4]]
b -  [[5 6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [38]:
a = np.array([[1, 2, 3, 4]])
print a.T

[[1]
 [2]
 [3]
 [4]]
